---
apiVersion: v1
kind: Secret
metadata:
  name: oci-cluster-identity-secret
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  tenancy: ${OCI_TENANCY}
  user: ${OCI_USER}
  key: ${OCI_KEY}
  fingerprint: ${OCI_FINGERPRINT}
  region: ${OCI_REGION}
  compartment: ${OCI_COMPARTMENT}
  vcn: ${OCI_VCN}
  subnet1: ${OCI_SUBNET1}
  subnet2: ${OCI_SUBNET2}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIClusterIdentity
metadata:
  name: oci-cluster-identity
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
spec:
  type: UserPrincipal
  principalSecret:
    name: oci-cluster-identity-secret
    namespace: ${NAMESPACE}
  allowedNamespaces: {}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: oci-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: OCI credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIClusterIdentity
    name: oci-cluster-identity
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-cluster-identity-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
data:
  configmap.yaml: |
    {{- $$secret := (getResource "InfrastructureProviderIdentitySecret") -}}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: oci-cloud-controller-manager
      namespace: kube-system
    type: Opaque
    data:
      cloud-provider.yaml: |
        auth:
          tenancy: {{ $$secret.data.tenancy }}
          user: {{ $$secret.data.user }}
          key: {{ $$secret.data.key }}
          fingerprint: {{ $$secret.data.fingerprint }}
          region: {{ $$secret.data.region }}
        compartment: {{ $$secret.data.compartment }}
        vcn: {{ $$secret.data.vcn }}
        loadBalancer:
          subnet1: {{ $$secret.data.subnet1 }}
          subnet2: {{ $$secret.data.subnet2 }}
          securityListManagementMode: {{ $$secret.data.securityListManagementMode | default "All" }}
