---
apiVersion: v1
kind: Secret
metadata:
  name: oci-cluster-identity-secret
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  tenancy: ${OCI_TENANCY}
  user: ${OCI_USER}
  key: |
${OCI_KEY}
  fingerprint: ${OCI_FINGERPRINT}
  region: ${OCI_REGION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIClusterIdentity
metadata:
  name: oci-cluster-identity
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
spec:
  type: UserPrincipal
  principalSecret:
    name: oci-cluster-identity-secret
    namespace: ${NAMESPACE}
  allowedNamespaces: {}
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: oci-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: OCI credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIClusterIdentity
    name: oci-cluster-identity
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-cluster-identity-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
data:
  configmap.yaml: |
    {{- $$cluster := .InfrastructureProvider -}}
    {{- $$secret := (getResource "InfrastructureProviderIdentitySecret") -}}
    {{- $$cloudProvider := dict
      "auth" (dict
        "tenancy" ($$secret.data.tenancy | b64dec)
        "user" ($$secret.data.user | b64dec)
        "key" ($$secret.data.key | b64dec)
        "fingerprint" ($$secret.data.fingerprint | b64dec)
        "region" ($$secret.data.region | b64dec)
      )
      "compartment" $$cluster.spec.compartmentId
      "vcn" $$cluster.spec.networkSpec.vcn.id
      "loadBalancer" (dict
        "disabled" true
      )
    -}}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: oci-cloud-controller-manager
      namespace: kube-system
    type: Opaque
    data:
      cloud-provider.yaml: {{ $$cloudProvider | toYaml | b64enc }}
