---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-oci-0-2-1
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-oci
      version: 0.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
